server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: ${SIGNING_KEY}
  valid-duration: 86400 # in second
  refreshable-duration: 172800  # in seconds

# TEST
#  valid-duration: 20 # in second
#  refreshable-duration: 120 # in seconds
payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "A3JJWFNP"
    secretKey: ${SECRET_KEY}
    returnUrl: "http://localhost:3000/payment-callback"
    version: "2.1.0"
    command: "pay"
    orderType: "other"